### PR TITLE
bump bc watch initial wait to 10 sec

### PR DESCRIPTION
**Pull request by gabemontero**
fixes https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/102 (or at least mitigates it)

@bparees @jimmidyson PTAL / FYI

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by bparees** [comment]
@jimmidyson can you do a new release w/ this change? and/or grant @gabemontero and myself permissions to do releases.  (if i have that permission already, i'm hitting some other issue and i'll have @gabemontero take a look at my steps tomorrow)

**Comment by jimmidyson** [comment]
Because this is still under the io.fabric8 group ID, they have to be signed with the appropriate fabric8 gpg key so I'll have to do the release - which I'm doing now.

**Comment by jimmidyson** [comment]
Available now - https://repo.jenkins-ci.org/releases/io/fabric8/jenkins/plugins/openshift-sync/0.0.14/

**Comment by bparees** [comment]
awesome, thanks @jimmidyson!

**Pull request merged**
