### PR TITLE
retry on exising job load collsion after jenkins restart

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-sync-plugin/issues/117

@bparees @jimmidyson

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero do you want to make this change here first: 
https://github.com/openshift/jenkins-sync-plugin
?

**Comment by jimmidyson** [comment]
I didn't get around to trying it but @scoheb made the [suggestion](https://github.com/openshift/jenkins-sync-plugin/issues/109) to use `ItemListener.html.onLoaded` which might be a cleaner solution to this problem.

**Comment by gabemontero** [comment]
Did I do it to the wrong repo ?!?!?!?!

Ok I'll cancel this one and redo.

**Comment by gabemontero** [comment]
Hmm. Yeah I've used that plug point before.

Have to redo the pull anyway I'll look into onLoaded.  At first blush I
agree it could help with the update path.  Not 100% sure about create yet.

**Comment by bparees** [comment]
> Did I do it to the wrong repo ?

well neither repo is wrong and at least until we put some CI in place somewhere it doesn't matter all that much, but the pattern i think we've been following on the other plugins is to change the openshift org fork first, then push the change up to the jenkinsci fork.

**Comment by gabemontero** [comment]
On Mon, Feb 27, 2017 at 8:57 PM Ben Parees <notifications@github.com> wrote:

> Did I do it to the wrong repo ?
>
> well neither repo is wrong and at least until we put some CI in place
> somewhere it doesn't matter all that much, but the pattern i think we've
> been following on the other plugins is to change the openshift org fork
> first, then push the change up to the jenkinsci fork.
>
yea i meant i did it in the wrong order...i certainly knew that was the
pattern...just can't believe i got it that backwards:-)

I'll double check my set up on my laptop and see what i had miswired

**Comment by gabemontero** [comment]
Sure enough my local repo has the wrong upstream remote .... OK, cancelling this PR.  Will rework.

**Pull request closed without merging**
