### PR TITLE
Replace deprecated usage with non-deprecated equivalent

### PR DESCRIPTION
**Pull request by basil**
Replaces a usage of the deprecated `org.apache.commons.httpclient.HttpStatus` with a raw integer, which is not deprecated.

### CODE REVIEW

**Comment by basil** [comment]
CC @divyansh42 @akram @gabemontero

**Comment by basil** [comment]
I am planning to remove the library from Jenkins core so unless you want your plugin to break you will need to stop depending on it. I will introduce a constant into this class.

**Comment by akram** [comment]
@basil do you know in which Jenkins LTS release the new class with the constant will be available?
could it be possible to have a transition period?

cc @divyansh42

**Comment by basil** [comment]
Probably the LTS that comes out in March 2023. And we are already in the transition period: the class you are importing is already deprecated.

**Comment by basil** [comment]
The 2.379 weekly release that shipped today no longer contains Commons HttpClient 3.x, so this PR will need to be merged and released in order for this plugin to remain working on weekly releases.

**Pull request closed without merging**
