### PR TITLE
support syncing multiple namespaces

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal

**Comment by gabemontero** [comment]
@bparees did you channel me for a second and submit a PR to jenkinsci/openshift-sync-plugin vs. openshift/jenkins-sync-plugin accidentally ?

**Comment by bparees** [comment]
@gabemontero no, i submitted the PR to the openshift repo, merged it, and then pushed the commit to the jenkinsci repo.

**Comment by bparees** [comment]
@gabemontero what workflow do you use?

**Comment by gabemontero** [comment]
@bparees and I discussed offline

I'll approve and merge this PR.

**Pull request merged**
