### PR TITLE
Fixes startup ordering, especially an issue blocking Jenkins startup (oops!)

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by willemvd** [comment]
Can this be fixed asap? 
This is blocking my installation, since it fails permanently to startup my Jenkins

**Comment by jimmidyson** [comment]
Was waiting on a review, should be in today & released later. Out of interest, how are you using this? Via the RHEL test image? It's not in the Origin Jenkins image yet AFAIK (waiting on https://github.com/openshift/jenkins/pull/204 which is blocked by this).

**Comment by willemvd** [comment]
I used the jenkins-persistent image and then updated all the plugins (we need to run all the plugins with the latest version since this is required by policy)

**Comment by jimmidyson** [comment]
Ah OK - wonder if I can pull that release from Jenkins update site somehow.

**Comment by jimmidyson** [comment]
Self-merging... if anyone has time to post-merge review I can fix up anything you find.

**Comment by jimmidyson** [comment]
@willemvd Released 0.1.1 - will be indexed to Jenkins update centre in a few hours from experience.

**Comment by willemvd** [comment]
Great, thanks!

2016-11-23 13:45 GMT+01:00 Jimmi Dyson <notifications@github.com>:

**Pull request merged**
